database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: database
  # Lásd: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  pool-size: 2
  async: true
  tables:
    bans: "achilles_bans"
    mutes: "achilles_mutes"
    kicks: "achilles_kicks"
    blacklist: "achilles_blacklists"
    alts: "achilles_alts"
# Redis messenger
messenger:
  # SQL vagy REDIS
  type: SQL

  # Az alap adatbáziscsatlakozást fogja felhasználni ebben az esetben.
  sql:
    poll-rate: 20
    housekeep-threshold: 30
    message-timestamp-limit: 30
    table-name: "achilles_messages"

  redis:
    host: 127.0.0.1
    port: 6379
    auth:
      authenticate: false
      password: password
server-name: "Test"
save-alts: false
  #Placeholderek:
  # {executor}
  # {target}
  # {server} (only works on "alert-message")
  # {silent} (gets replaced with the punishment"s "silent" string)

  # TIP: Többsoros üzenethez hastnálj "|-"-t a ":" után
  # pl.:
  # usage: |-
  #   multi
  #   lined!
  #   usage.
punishments:
  kick:
    usage: "&6Usage: &f/kick &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been kicked by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been kicked by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
    punishment-message: "&cYou got kicked."
  ban:
    usage: "&6Usage: &f/ban &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been banned permanently by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been banned permanently by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
    punishment-message: "&cYour account is permanently banned from the server."
  mute:
    usage: "&6Usage: &f/mute &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been muted permanently by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been muted permanently by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
    punishment-message: "&cYou can't talk, because you permanently are muted."
  blacklist:
    usage: "&6Usage: &f/blacklist &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been blacklisted by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been blacklisted by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
    punishment-message: "&cYour account is blacklisted from the server."
  tempban:
    usage: "&6Usage: &f/tempban &7<player> <time> [reason] [-s]"
    message: "{silent}&e{target} &fhas been banned temporarily by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been banned temporarily by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
    punishment-message: "&cYour account is temporarily banned from the server."
  tempmute:
    usage: "&6Usage: &f/tempmute &7<player> <time> [reason] [-s]"
    message: "{silent}&e{target} &fhas been muted temporarily by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been muted temporarily by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
    punishment-message: "&cYou can't talk, because you are temporarily muted."
  unban:
    usage: "&6Usage: &f/unban &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been unbanned by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been unbanned by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
  unmute:
    usage: "&6Usage: &f/unmute &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been unmuted by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been unmuted by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"
  unblacklist:
    usage: "&6Usage: &f/unblacklist &7<player> [reason] [-s]"
    message: "{silent}&e{target} &fhas been unblacklisted by &6{executor}"
    alert-message: "{silent}&7[{server}] &e{target} &fhas been unblacklisted by &6{executor}"
    silent: "&7&o[Silent]&r "
    default-reason: "Not defined. -s"

# Egyéb
already-punished: "&cThis player is already punished."
override-reason: "Overridden by {sender}"
failed-to-load-player-profile: "&cSomething went wrong while tried to load target's profile."
target-is-offline: '&cTarget is offline!'
no-permission: "&cYou don't have enough permission!"
no-permission-to-override: "&cYou don't have enough permissions to override an existing punishment."
not-punished: "&cThis player is not punished."
console-name: "~CONSOLE"

date-formatting:
  pattern-settings:
    # Lásd: Java simple date formatting
    pattern: "yyyy.MM.dd hh:mm"
    # Lásd: IETF locales
    locale: "en-US"
  year: "year"
  years: "years"
  month: "month"
  months: "months"
  week: "week"
  weeks: "weeks"
  day: "day"
  days: "days"
  hour: "hour"
  hours: "hours"
  minute: "minute"
  minutes: "minutes"
  second: "second"
  seconds: "seconds"
  permanent: "never"
  expired: "expired"

alts:
  check-message: |-
    Checking alts for player {player}...
    &7[&cBanned&7, &aOnline&7, &fOffline&7]
  separator: "&7, "
  online: "&a{player}"
  banned: "&c{player}"
  offline: "&f{player}"

punishment:
  active:
    true: "&aYes"
    false: "&cNo"