main: me.marvin.achilles.Achilles
name: achilles
version: 0.1-alpha
author: marvin
website: https://github.com/marvintheskid/achilles

commands:
  ban:
permissions:
  achilles.*:
    children:
      - achilles.checkalts
      - achilles.ban.*
    description: Master permission.
    default: false
  achilles.alerts:
    description: Alert permission.
    default: false
  achilles.checkalts:
    description: Permission for checking alts.
    default: false
  achilles.ban.*:
    children:
      - achilles.ban.issue
      - achilles.ban.lift
      - achilles.ban.override
    description: Permission for banning players.
    default: false
  achilles.ban.issue:
    description: Permission for banning players.
    default: false
  achilles.ban.lift:
    description: Permission for unbanning players.
    default: false
  achilles.ban.override:
    description: Permission for overriding existing bans.
    default: false